### ISSUE TITLE
Adding location type response from susi line bot

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/susi_linebot#1]
**Actual Behaviour**

Currently line bot doesn't return location on query like where is Singapore?

**Expected Behaviour**

It should return location response with map. 

**Steps to reproduce it**

I will send location response with location type message for line node js api. 

**Would you like to work on the issue?**

Yes

**Comment by AliAyub007** [comment]
Line bot uses reply token to reply for any message event and it can be used only once for one message. 
But in location type response from SUSI we have to send all actions as message to user  i.e answer and map type. 

![map](https://user-images.githubusercontent.com/25840461/27254192-e6a6d316-539c-11e7-810f-80f7a9fa4dd2.PNG)

we return response like this. 

const answer = {
                "type": "location",
                "title": "Location",
                "address": "Location",
                "latitude": lat,
                "longitude": lon
            };

            // use reply API
            return client.replyMessage(event.replyToken, answer);

For map we have to send text type message first and then location type. Is there any way that we can bypass it and send all actions?

**Comment by Manveer695** [comment]
one way we can think of it, is before returning with client.reply(), we can request our webhook url again with an object in a request and reply to it with the second message. Like after replying with 1st message we can request our webhook url again with an object which indicates that 1st message is done and now this request is to send the second message. Can we work it that way?

**Comment by AliAyub007** [comment]
@Manveer695 No need of this I solved it by sending array of messages containing different message types.
